In [103]:
import numpy as np 
import pandas as pd
l=[" iphone-14 Pro ",
"SAMSUNG galaxy S23",
"oneplus_11",
"Pixel--7 Pro",
" xiaomi 13 "]
a=np.array(l)
a

array([' iphone-14 Pro ', 'SAMSUNG galaxy S23', 'oneplus_11',
       'Pixel--7 Pro', ' xiaomi 13 '], dtype='<U18')

In [145]:

def rep(s):
    r=s.replace("_"," ")
    t=r.replace("-"," ")
    u=t.replace("  "," ")
    print(u.strip().capitalize())
f=filter(rep,a)
print(list(f))


Iphone 14 pro
Samsung galaxy s23
Oneplus 11
Pixel 7 pro
Xiaomi 13
[]


In [146]:
s=input("Enter password: ")
l=len(s)
lw=u=sc=r=0
for i in s:
    if i.islower()==True:
        lw=1
    elif i.isupper()==True:
        u=1
    elif i.isdigit()==True:
        d=1
    else:
        sc=1

        
if l>=8 and lw==1 and u==1 and d==1 and sc==1:
    print("strong")
elif l<=8 or lw==0 or u==0 or d==0 or sc==0:
    print("moderate")
else:
    print("weak")

Enter password:  pionEER123#


strong


In [157]:
l=[" alice ", "BOB", "ChArLie", " david"]
l1=[]
for i in l:
    r=i.replace(" ","")
    l1.append(r)

s=pd.Series(l1)
print(s)

0      alice
1        BOB
2    ChArLie
3      david
dtype: object


In [168]:
a=np.random.randint(1,100,size=100)
b=np.array(np.split(a,10))
print(b)
i=j=0
for i in 10:
    for j in 10:
        if a[i][j]>=50:
            print(a[i][j])

[[21 14 94 11 73 69 34 19 35 50]
 [ 2 79 30 41 41 25 91 78 88 91]
 [17 35 40 45 31 74 86 39 77 52]
 [69 43  2 16 70 30 12 53  8 25]
 [81 62 90 63 29 32 95 96  9 39]
 [82  3 20 14 80 81 75 75 31 63]
 [23 99 71 65 43  7 86 20 82  9]
 [17 49 68 68 59 53 46 86 41 82]
 [15 54 12 82 82  3 87  2 56 84]
 [72 43 27 96 26 26 92 31 55  1]]


TypeError: 'int' object is not iterable

In [172]:
a=np.array([1,2,3],[4,5,6])
a1=np.array([7,8,9],[1,2,8])
b=a*a1
print(b)

TypeError: Field elements must be 2- or 3-tuples, got '4'

In [3]:

import numpy as np
import pandas as pd

a=np.arrange(1,11,size=6)
a1=np.split(a,2)

b=np.arrange(1,11,size=6)
b1=np.split(b,2)

c=a1*b1

AttributeError: module 'numpy' has no attribute 'arrange'